# Copyright 2023, Helmholtz-Zentrum Hereon
# SPDX-License-Identifier: CC0-1.0

[build-system]
requires = ["setuptools", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "pydidas"
authors = [{name = "Malte Storm"}]
description = "pydidas - the PYthon DIffraction Data Analysis Suite"
readme = "README.rst"
requires-python = ">=3.11"
license = {text = "GNU General Public License v3"}
keywords = ["X-ray diffraction", "XRD", "WAXS", "SAXS"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Physics",
]
dynamic = ["version"]
dependencies = [
    "meson-python",
    "cython",
    "build>=0.10.0",
    "pyFAI>=2023.1.0",
    "scikit-image>=0.20.0",
    "qtawesome>=1.0.3",
    "sphinx>=4.4.0",
    "sphinx_rtd_theme>=1.0.0",
    "pyopencl>=2023.1",
    "qtpy>=2.3.0",
    "hdf5plugin>=4.0.1",
    "pyyaml>=6.0",
    "requests>=2.31.0",
    "PyQt5",
]

[project.urls]
homepage = "https://ms.hereon.de/pydidas"
# documentation = "https://readthedocs.org"
repository = "https://github.com/hereon-GEMS/pydidas"
changelog = "https://github.com/hereon-GEMS/pydidas/blob/master/CHANGELOG.md"

[tool.setuptools.dynamic]
version = {attr = "pydidas.version.VERSION"}

[tool.setuptools]
packages = ["pydidas", "pydidas_scripts", "pydidas_plugins", "pydidas_qtcore"]

[project.scripts]
pydidas-clear-qsettings = "pydidas_scripts.clear_pydidas_qsettings:clear_pydidas_QSettings"
pydidas-updater = "pydidas_scripts.pydidas_updater_script:run_update"
pydidas-documentation = "pydidas_scripts.pydidas_documentation:open_pydidas_documentation"
pydidas-remove-gui-state-files = "pydidas_scripts.pydidas_remove_local_files:pydidas_remove_stored_gui_states"
run-pydidas-workflow = "pydidas_scripts.run_pydidas_workflow:run_workflow" 

[project.gui-scripts]
pydidas-gui = "pydidas_scripts.pydidas_gui:run_gui"

[tools.coverage.report]
omit = ['*/tests/*']

[tool.isort]
profile = 'black'
extend_skip = ["__init__.py"]
lines_after_imports = 2

[tool.black]
line-length = 88
target-version = ['py39']