[build-system]
requires = [
    "setuptools",
    "wheel",
    "build",
]
build-backend = "setuptools.build_meta"

[tools.coverage.report]
omit = ['*/tests/*']


[tool.black]
line-length = 88
target-version = ['py39']