# This file is part of pydidas.
#
# Copyright 2024, Helmholtz-Zentrum Hereon
# SPDX-License-Identifier: CC-BY-4.0
#
# This workflow will check the formatting of the newly pushed commits
# to verify that all files are corretly formatted.


name: formatting checks

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  code_check_setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Check out source repository
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install black
        python -m pip install reuse
        python -m pip install isort

  check_black:
    needs: code_check_setup
    runs-on: ubuntu-latest
    steps:
    - name: Code formatting with black
      run: |
        python -m black . --check

  check_flake8:
    needs: code_check_setup
    runs-on: ubuntu-latest
    steps:
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 --config .flake8 --exit-zero
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide

  check_reuse:
    needs: code_check_setup
    runs-on: ubuntu-latest
    steps:
    - name: Reuse check
      uses: fsfe/reuse-action@v2

  check_isort:
    needs: code_check_setup
    runs-on: ubuntu-latest
    steps:
    - name: isort checks
      uses: isort/isort-action@master
