# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pydidas formatting checks

on:
  push:
    branches: [ "github-workflows" ]
  pull_request:
    branches: [ "github-workflows" ]

jobs:

  code_checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install black
        python -m pip install reuse
        python -m pip install isort

    - name: Code formatting with black
      run: |
        python -m black . --check
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 --config .flake8 --exit-zero
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Reuse check
      uses: fsfe/reuse-action@v2
    - name: isort checks
      uses: isort/isort-action@master
